// 遊戲流程
export enum GameState {
    None = "",
    Load = "Load",
    Init = "Init",
    Wait = 0,
    NGBeforeSpin = "NGBeforeSpin",
    NGSpin = 1000,
    FeaturePlay = "FeaturePlay",
    Remove = "Remove",
    MultipleHandle = "MultipleHandle",
    BeforeShowWin = "BeforeShowWin",
    NGShowWin = 1001,
    NGComplete = 1002,
    FGTrigger = "FGTrigger",
    FGWait = "FGWait",
    FGBeforeSpin = "FGBeforeSpin",
    FGSpin = "FGSpin",
    FGFeaturePlay = "FGFeaturePlay",
    FGRemove = "FGRemove",
    FGMultipleHandle = "FGMultipleHandle",
    FGBeforeShowWin = "FGBeforeShowWin",
    FGShowWin = "FGShowWin",
    FGComplete = "FGComplete",
}